server:
  port: 8088

spring:
  application:
    name: eureka-zuul

zuul:
  # 路由前缀
  prefix: /api
  # 声明路由
  routes:
    xxx-service: /manage/**
    search-server: /search/**
    user-server: /user-conter/**  #用户请求
    oauth-server: /oauth/** #登录请求
    car-server: /car/** #购物车
    order-server: /order/** #订单请求
    # 路由名称
#    api-xxx:
#      # 声明将所有以/api-ribbon/的请求都转发到eureka-ribbon的服务中
#      path: /api-xxx/**
#      serviceId: xxx-service
    #搜索路由
#    api-search:
#      path: /api-search/**
#      serviceId: search-server

  # 启用重试
  retryable: true

  # 包含此路径的不进行路由
  ignored-patterns: /upload/**
  # 忽略上传服务
  ignored-services:
    -upload-server
  #登录
  add-host-header: true #将域名添加到请求头中
  sensitive-headers:    #set-cookie方法被zuul禁止,将属性设置为空,代表启用set-cookie


#配置负载
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：6000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mrshop:
  #声明不进行拦截的请求用,分隔
  filter:
    excludes: /api/oauth/oauth/login,/api/user-center/user/register,/api/oauth/oauth/verify
  jwt:
    pubKeyPath: D:\idea-projects\rea.pub # 公钥地址(私钥加密,公钥解密)
    cookieName: MRSHOP_TOKEN
