server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mr:
  upload:
    path:
      windows: D:\\images
      linux: /xiaopengyan/images
    img:
      host: http://image.mrshop.com